; PlatformIO Project Configuration File for BalanceBoard-Gamepad Firmware

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    andremmfaria/ESP32Wiimote @ ^2.0.0
